#!/usr/bin/env node
// Builds lib/engine.mjs: a pure-Node bundle of the DrawCMS editor's headless
// document builder (createDocumentFromWebMCP) and validator
// (validateDiagramVisualGrammar), plus the vocabulary constants. The editor
// package ships TypeScript source and pulls @xyflow/react for a single enum, so
// we bundle from an exact packed release (never a sibling checkout — see the
// workspace editor->cloud boundary rule) with the browser library stubbed.
//
// Usage:
//   node scripts/build-engine.mjs                 # (re)build lib/engine.mjs
//   node scripts/build-engine.mjs --check         # fail if lib/engine.mjs is stale/missing
//   DRAWCMS_EDITOR_TGZ=/path/to.tgz node scripts/build-engine.mjs

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, rmSync, mkdirSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const OUT = join(ROOT, "lib", "engine.mjs");
const STUB = join(HERE, "xyflow-stub.mjs");

// Pinned so the engine is reproducible; override with DRAWCMS_EDITOR_TGZ.
const EDITOR_VERSION = "0.17.2";
const ZOD_VERSION = "3.25.76";
const NANOID_VERSION = "5.1.7";
const ESBUILD_VERSION = "0.25.4";

function resolveTarball() {
  if (process.env.DRAWCMS_EDITOR_TGZ) return resolve(process.env.DRAWCMS_EDITOR_TGZ);
  // Default location: the cloud repo's vendored release, one level up.
  const vendored = resolve(ROOT, "..", "drawcms-cloud", "vendor", `drawcms-editor-${EDITOR_VERSION}.tgz`);
  if (existsSync(vendored)) return vendored;
  throw new Error(
    `Could not find the editor tarball. Expected ${vendored}. ` +
      `Set DRAWCMS_EDITOR_TGZ to an exact packed @drawcms/editor release.`,
  );
}

function buildBundle(tgz) {
  const work = mkdtempSync(join(tmpdir(), "drawcms-engine-"));
  try {
    execFileSync("tar", ["-xzf", tgz], { cwd: work, stdio: "pipe" });
    writeFileSync(join(work, "package-min.json"), JSON.stringify({ name: "engine-build", private: true }));
    // Install only the runtime deps the engine graph actually needs.
    execFileSync(
      "npm",
      ["install", "--no-save", "--no-package-lock", `zod@${ZOD_VERSION}`, `nanoid@${NANOID_VERSION}`, `esbuild@${ESBUILD_VERSION}`],
      { cwd: work, stdio: "pipe" },
    );
    const entry = join(work, "entry.mjs");
    writeFileSync(
      entry,
      [
        'export { createDocumentFromWebMCP } from "./package/src/webmcp/tools.ts";',
        'export {',
        "  WEBMCP_NODE_TYPES,",
        "  WEBMCP_EDGE_TYPES,",
        "  WEBMCP_NODE_MOTION_PRESETS,",
        "  WEBMCP_EDGE_MOTION_PRESETS,",
        '} from "./package/src/webmcp/tools.ts";',
        'export {',
        "  validateDiagramVisualGrammar,",
        "  recommendVisualGrammar,",
        "  getVisualElementGrammar,",
        "  getVisualMotionGrammar,",
        "  VISUAL_DIAGRAM_TYPES,",
        "  VISUAL_ELEMENT_REGISTRY,",
        "  VISUAL_MOTION_REGISTRY,",
        '} from "./package/src/webmcp/visual-grammar.ts";',
        "// applyGraphEditOperations is the pure, editor-independent applier for",
        "// incremental graph edits (add/update/delete node/edge). It is what backs",
        "// `drawcms edit`, letting a surgical change apply to a pulled document",
        "// without a full rebuild that would discard human-authored positions.",
        'export { applyGraphEditOperations } from "./package/src/commands/commands.ts";',
        "",
        "// Baked-in provenance so the CLI can report which editor release it builds against.",
        `export const ENGINE_EDITOR_VERSION = ${JSON.stringify(readEditorVersion(work))};`,
      ].join("\n"),
    );
    const esbuild = join(work, "node_modules", ".bin", "esbuild");
    execFileSync(
      esbuild,
      [
        entry,
        "--bundle",
        "--format=esm",
        "--platform=node",
        `--alias:@xyflow/react=${STUB}`,
        `--outfile=${join(work, "bundle.mjs")}`,
      ],
      { cwd: work, stdio: "pipe" },
    );
    return readFileSync(join(work, "bundle.mjs"), "utf8");
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

function readEditorVersion(work) {
  try {
    const pkg = JSON.parse(readFileSync(join(work, "package", "package.json"), "utf8"));
    return pkg.version ?? EDITOR_VERSION;
  } catch {
    return EDITOR_VERSION;
  }
}

function banner(source) {
  const hash = createHash("sha256").update(source).digest("hex").slice(0, 12);
  return (
    `// GENERATED by scripts/build-engine.mjs — do not edit by hand.\n` +
    `// Bundled from @drawcms/editor ${EDITOR_VERSION}. Rebuild with: npm run build:engine\n` +
    `// content-sha256:${hash}\n`
  );
}

const check = process.argv.includes("--check");
const tgz = resolveTarball();
const bundle = buildBundle(tgz);
const output = banner(bundle) + bundle;

if (check) {
  if (!existsSync(OUT)) {
    console.error("lib/engine.mjs is missing. Run: npm run build:engine");
    process.exit(1);
  }
  const current = readFileSync(OUT, "utf8");
  // Compare on the bundle body, ignoring the banner's own hash line for stability.
  const strip = (s) => s.replace(/\/\/ content-sha256:[a-f0-9]+\n/, "");
  if (strip(current) !== strip(output)) {
    console.error("lib/engine.mjs is stale. Run: npm run build:engine");
    process.exit(1);
  }
  console.log("lib/engine.mjs is up to date.");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, output);
  console.log(`Wrote ${OUT} (${output.length} bytes) from editor ${EDITOR_VERSION}.`);
}
